# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'NeilDo'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
  - name: Featured Projects
    submenu:
      - name: MicroBam
        link: /projects/microbam
      - name: OurLegacy
        link: /projects/ourlegacy
  - name: Posts
    link: /
  - name: Tags
    link: /tags
  - name: About
    link: /about
  - name: Follow me
    submenu:
      - name: GitHub
        icon: github
        link: https://neil-do.github.io
      - name: LinkedIn
        icon: linkedin-square
        link:
      - name: Twitter
        icon: twitter
        link: https://twitter.com/Neil_D0
